spring.application.name=PetFriends_Transporte

# Servidor
server.port=8082

# Banco de dados (Postgres via Docker Compose)
spring.datasource.url=jdbc:postgresql://localhost:5434/transporte_db
spring.datasource.username=petfriends
spring.datasource.password=petfriends
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

